/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.KhoDao;
import Model.KHO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class KhoBai extends javax.swing.JPanel {

    /**
     * Creates new form KhoBai
     */
    private DefaultTableModel tblModel;
    public KhoBai() {
        initComponents();
        initTable();
        loadDataToTable();
    }
    
    private String CreateID() throws Exception{
        List<KHO> list = new KhoDao().findAll();  
        if (list.size()!=0) {
            int index = list.size()-1;
            KHO kho = list.get(index);
            int idNumber = Integer.parseInt(kho.getId_kho().substring(3)) + 1; //id next        
            if (idNumber < 10) {
                return "kho0"+String.valueOf(idNumber);
            }
            return "kho"+String.valueOf(idNumber);
        }
        return "kho01";
    }
    
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"ID kho","Ten kho","Loai Kho","Dia chi"});
        tblkho.setModel(tblModel);
    }
    
    private void loadDataToTable(){
        try {
            KhoDao dao = new KhoDao();
            List<KHO> list = dao.findAll();
            tblModel.setRowCount(0);
            for(KHO kho : list){
                tblModel.addRow(new Object[]{
                    kho.getId_kho(),
                    kho.getTen_kho(),
                    kho.getLoai_kho(),
                    kho.getDia_chi()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidkho = new javax.swing.JTextField();
        txttenkho = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        btnMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtloaikho = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkho = new javax.swing.JTable();

        jpnRoot.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setText("ID kho");

        jLabel2.setText("Ten Kho");

        jLabel3.setText("Loai kho");

        jLabel4.setText("Dia chi");

        txtidkho.setEditable(false);
        txtidkho.setBackground(new java.awt.Color(204, 204, 204));

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-document.png"))); // NOI18N
        btnMoi.setText("Lam moi");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/floppy-disk.png"))); // NOI18N
        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        btnCapNhat.setText("Cap nhat");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidkho)
                            .addComponent(txttenkho)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(txtloaikho))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLuu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidkho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttenkho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtloaikho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoi)
                    .addComponent(btnLuu)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        tblkho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblkho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkhoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblkho);

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        try {
            txtidkho.setText(CreateID());
        } catch (Exception ex) {
            Logger.getLogger(KhoBai.class.getName()).log(Level.SEVERE, null, ex);
        }
        txttenkho.setText("");
        txtloaikho.setText("");
        txtdiachi.setText("");
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(txtidkho.getText().equals("")) sb.append("Ban chua nhap ID kho");
        else if(txttenkho.getText().equals("")) sb.append("Ban chua nhap ten kho");
        else if(txtloaikho.getText().equals("")) sb.append("Ban chua nhap loai kho");
        else if(txtdiachi.getText().equals("")) sb.append("Ban chua nhap dia chi kho");
        if(sb.length()>0){
           JOptionPane.showMessageDialog(this, sb);
           return;
        }
        try {
            KHO kho = new KHO();
            kho.setId_kho(txtidkho.getText());
            kho.setTen_kho(txttenkho.getText());
            kho.setLoai_kho(txtloaikho.getText());
            kho.setDia_chi(txtdiachi.getText());
            
            if(new KhoDao().insert(kho)){
                JOptionPane.showMessageDialog(this,"Kho da duoc them vao CSDL");
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Them khong thanh cong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Ban co muon cap nhat kho hang khong?") == JOptionPane.NO_OPTION){
            return;
        }
        try {
            KHO kho = new KHO();
            kho.setId_kho(txtidkho.getText());
            kho.setTen_kho(txttenkho.getText());
            kho.setLoai_kho(txtloaikho.getText());
            kho.setDia_chi(txtdiachi.getText());
            if (new KhoDao().update(kho)) {
                JOptionPane.showMessageDialog(this,"kho da duoc cap nhat vao CSDL");
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Cap nhat khong thanh cong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Ban co muon xoa kho khong?") == JOptionPane.NO_OPTION){
            return;
        }
        try {
            if (new KhoDao().delete(txtidkho.getText())) {
                JOptionPane.showMessageDialog(this,"Kho da duoc xoa khoi CSDL");
                btnMoiActionPerformed(evt);
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Xoa khong thanh cong");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblkhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkhoMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblkho.getSelectedRow();
            if(row >= 0){
                String id = (String) tblkho.getValueAt(row,0);
                KhoDao dao = new KhoDao();
                KHO kho = dao.findByID(id);
                System.out.println("id kho: "+id);

                if(kho != null){
                    txtidkho.setText(kho.getId_kho());
                    txttenkho.setText(kho.getTen_kho());
                    txtloaikho.setText(kho.getLoai_kho());
                    txtdiachi.setText(kho.getDia_chi());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblkhoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JTable tblkho;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtidkho;
    private javax.swing.JTextField txtloaikho;
    private javax.swing.JTextField txttenkho;
    // End of variables declaration//GEN-END:variables
}
