/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.NhanVienDao;
import Model.NHANVIEN;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NhanVien extends javax.swing.JPanel {

    /**
     * Creates new form NhanVien
     */
    
    private DefaultTableModel tblModel;
    public NhanVien() {
        initComponents();
        initTable();
        loadDataToTable();
    }

    private String CreateID() throws Exception{
        List<NHANVIEN> list = new NhanVienDao().findAll(""); 
        if (list.size()!=0) {
            int index = list.size()-1;
            NHANVIEN nv = list.get(index); 
            int idNumber = Integer.parseInt(nv.getId_nv().substring(2)) + 1; //id next        
            if (idNumber < 10) {
                return "nv00"+String.valueOf(idNumber); // =>"nv002"
            }
            else if (idNumber >= 10 && idNumber <100) {
                return "nv0"+String.valueOf(idNumber);
            }
            return "nv"+String.valueOf(idNumber);
        }
        return "nv001";
    }
    
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"ID nhan vien","Ho","Ten","Ngay sinh","Phai","Sdt","Tai_khoan","Ma khau"});
        tblNhanVien.setModel(tblModel);
    }
    
    private void loadDataToTable(){
        try {
            String key = txttimkiem.getText();
            NhanVienDao dao = new NhanVienDao();
            List<NHANVIEN> list = dao.findAll(key);
            tblModel.setRowCount(0);
            for(NHANVIEN nv : list){
                tblModel.addRow(new Object[]{
                    nv.getId_nv(),
                    nv.getHo_nv(),
                    nv.getTen_nv(),
                    nv.getNgay_sinh(),
                    nv.getPhai(),
                    nv.getStd(),
                    nv.getTai_khoan(),
                    nv.getMat_khau()
                });
            }
            //System.out.println("tu tim kiem : " + key);
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpnRoot = new javax.swing.JPanel();
        jpnInputInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidnv = new javax.swing.JTextField();
        txthonv = new javax.swing.JTextField();
        txttennv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jrbNam = new javax.swing.JRadioButton();
        jrbNu = new javax.swing.JRadioButton();
        txtsdt = new javax.swing.JTextField();
        txttk = new javax.swing.JTextField();
        txtmk = new javax.swing.JTextField();
        btnMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jdcngaysinh = new com.toedter.calendar.JDateChooser();
        txttimkiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();

        jpnRoot.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("ID nhan vien");

        jLabel2.setText("Ho nhan vien");

        jLabel3.setText("Ten nhan vien");

        jLabel4.setText("Ngay sinh");

        txtidnv.setEditable(false);
        txtidnv.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("Gioi tinh");

        jLabel6.setText("Sdt");

        jLabel7.setText("Tai khoan");

        jLabel8.setText("Mat khau");

        buttonGroup1.add(jrbNam);
        jrbNam.setText("Nam");

        buttonGroup1.add(jrbNu);
        jrbNu.setText("Nu");

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-document.png"))); // NOI18N
        btnMoi.setText("Lam moi");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/floppy-disk.png"))); // NOI18N
        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        btnCapNhat.setText("Cap nhat");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnInputInfoLayout = new javax.swing.GroupLayout(jpnInputInfo);
        jpnInputInfo.setLayout(jpnInputInfoLayout);
        jpnInputInfoLayout.setHorizontalGroup(
            jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInputInfoLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnInputInfoLayout.createSequentialGroup()
                        .addGroup(jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidnv, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txthonv)
                            .addComponent(txttennv)
                            .addComponent(jdcngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(100, 100, 100)
                        .addGroup(jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpnInputInfoLayout.createSequentialGroup()
                                .addComponent(jrbNam)
                                .addGap(30, 30, 30)
                                .addComponent(jrbNu))
                            .addComponent(txtsdt)
                            .addComponent(txttk)
                            .addComponent(txtmk)))
                    .addGroup(jpnInputInfoLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnMoi)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapNhat)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jpnInputInfoLayout.setVerticalGroup(
            jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInputInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jrbNam)
                    .addComponent(jrbNu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txthonv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txttk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdcngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnInputInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoi)
                    .addComponent(btnLuu)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/seo.png"))); // NOI18N
        btnTimKiem.setText("Tim kiem");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnInputInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnInputInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        try {
            // TODO add your handling code here:
            txtidnv.setText(CreateID());
        } catch (Exception ex) {
            Logger.getLogger(NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        txthonv.setText("");
        txttennv.setText("");
        jdcngaysinh.setDate(null);
        txtsdt.setText("");
        txttk.setText("");
        txtmk.setText("");
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        StringBuilder sb = new StringBuilder();
        if(txthonv.getText().equals("")){
            sb.append("Ban chua nhap ho nhan vien");
        }
        else if(txttennv.getText().equals("")){
            sb.append("Ban chua nhap ten nhan vien");
        }
//        else if(dateFormat.format(jdcngaysinh.getDate()).equals("")){
//            sb.append("Ban chua chon ngay sinh");
//        } //error
        else if(!jrbNam.isSelected() && !jrbNu.isSelected()){
            sb.append("Ban chua chon gioi tinh");
        }
        else if(txtsdt.getText().equals("")){
            sb.append("Ban chua nhap sdt nhan vien");
        }
        else if(txttk.getText().equals("")){
            sb.append("Ban chua nhap ten dang nhap nhan vien");
        }
        else if(txtmk.getText().equals("")){
            sb.append("Ban chua nhap mat khau nhan vien");
        }
        if(sb.length()>0){
           JOptionPane.showMessageDialog(this, sb);
           return;
        }
        try {
            NHANVIEN nhanvien = new NHANVIEN();
            nhanvien.setId_nv(txtidnv.getText());
            nhanvien.setHo_nv(txthonv.getText());
            nhanvien.setTen_nv(txttennv.getText());
            nhanvien.setNgay_sinh(new SimpleDateFormat("yyyy-MM-dd").format(jdcngaysinh.getDate()));
            nhanvien.setPhai(jrbNam.isSelected()? "Nam" : "Nu");
            nhanvien.setStd(txtsdt.getText());
            nhanvien.setTai_khoan(txttk.getText());
            nhanvien.setMat_khau(txtmk.getText());
            if(new NhanVienDao().insert(nhanvien)){
                JOptionPane.showMessageDialog(this,"Nhan vien da duoc them vao CSDL");
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Them khong thanh cong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Ban co muon cap nhat nhan vien khong?") == JOptionPane.NO_OPTION){
            return;
        }
        try {
            NHANVIEN nhanvien = new NHANVIEN();
            nhanvien.setId_nv(txtidnv.getText());
            nhanvien.setHo_nv(txthonv.getText());
            nhanvien.setTen_nv(txttennv.getText());
            nhanvien.setNgay_sinh(new SimpleDateFormat("yyyy-MM-dd").format(jdcngaysinh.getDate()));
            nhanvien.setPhai(jrbNam.isSelected()? "Nam" : "Nu");
            nhanvien.setStd(txtsdt.getText());
//            nhanvien.setTai_khoan(txttk.getText());
//            nhanvien.setMat_khau(txtmk.getText());
            
            if(new NhanVienDao().update(nhanvien)){
                JOptionPane.showMessageDialog(this,"Nhan vien da duoc cap nhat vào CSDL");
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Cap nhat khong thanh cong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Ban co muon xoa nhan vien khong?") == JOptionPane.NO_OPTION){
            return;
        }
        try {
            NhanVienDao dao = new NhanVienDao();
            if (dao.delete(txtidnv.getText())) {
                JOptionPane.showMessageDialog(this,"Nhan vien da duoc xoa khoi CSDL");
                btnMoiActionPerformed(evt);
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Xoa khong thanh cong");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblNhanVien.getSelectedRow();
            if(row >= 0){
                String id = (String) tblNhanVien.getValueAt(row,0);
                NhanVienDao dao = new NhanVienDao();
                System.out.println("id nhan vien: "+id);
                System.out.println("dong so: "+row);
                NHANVIEN nv = dao.findByID(id);
                if(nv != null){
                    txtidnv.setText(nv.getId_nv());
                    txthonv.setText(nv.getHo_nv());
                    txttennv.setText(nv.getTen_nv());
                    jdcngaysinh.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(nv.getNgay_sinh()));
                    if(nv.getPhai().equals("Nam")) jrbNam.setSelected(true);
                    else jrbNu.setSelected(true);
                    txtsdt.setText(nv.getStd());
                    txttk.setText(nv.getTai_khoan());
                    txtmk.setText(nv.getMat_khau());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        loadDataToTable();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcngaysinh;
    private javax.swing.JPanel jpnInputInfo;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JRadioButton jrbNam;
    private javax.swing.JRadioButton jrbNu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txthonv;
    private javax.swing.JTextField txtidnv;
    private javax.swing.JTextField txtmk;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttennv;
    private javax.swing.JTextField txttimkiem;
    private javax.swing.JTextField txttk;
    // End of variables declaration//GEN-END:variables
}
