/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.NhaCCDao;
import Dao.NhanVienDao;
import Dao.PhieuNhapDao;
import Dao.VatTuDao;
import Model.NHACC;
import Model.NHANVIEN;
import Model.PHIEUNHAP;
import Model.VATTU;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NhapKho extends javax.swing.JPanel {

    /**
     * Creates new form NhapKho
     */
    private DefaultTableModel tblModel;
    private DefaultComboBoxModel cbxModel;
    public NhapKho() throws Exception {
        initComponents();
        initTable();
        loadDataToTable();
        initComboBox();
        if (Login.id.contains("ad")) {
            txtidnv.setText("");
        } else txtidnv.setText(Login.id);
    }

    private String CreateID() throws Exception{
        List<PHIEUNHAP> list = new PhieuNhapDao().findAll("");  
        if (list.size()!=0) {
            int index = list.size()-1;
            PHIEUNHAP pn = list.get(index);
            int idNumber = Integer.parseInt(pn.getId_pn().substring(2)) + 1; //id next        
            if (idNumber < 10) {
                return "pn00"+String.valueOf(idNumber);
            }
            else if (idNumber >= 10 && idNumber <100) {
                return "pn0"+String.valueOf(idNumber);
            }
            return "pn"+String.valueOf(idNumber);
        }
        return "pn001";
    }
    
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"ID phieu nhap","ID vat tu","ID nha cung cap","ID nhan vien","Ngay nhap","So luong nhap","Don gia nhap","Vi tri vat tu"});
        tblPhieuNhap.setModel(tblModel);
    }
    
    private void loadDataToTable(){
        try {
            String key = txttimkiem.getText();
            PhieuNhapDao dao = new PhieuNhapDao();
            List<PHIEUNHAP> list = dao.findAll(key);
            tblModel.setRowCount(0);
            for(PHIEUNHAP pn : list){
                if (pn.getId_nv().contains(Login.id)) {
                    tblModel.addRow(new Object[]{
                    pn.getId_pn(),
                    pn.getId_vt(),
                    pn.getId_nhacc(),
                    pn.getId_nv(),
                    pn.getNgay_nhap(),
                    pn.getSo_luong_nhap(),
                    pn.getDon_gia_nhap(),
                    pn.getVi_tri_vat_tu()
                    });
                }
                else if (Login.id.contains("ad")) {
                    tblModel.addRow(new Object[]{
                    pn.getId_pn(),
                    pn.getId_vt(),
                    pn.getId_nhacc(),
                    pn.getId_nv(),
                    pn.getNgay_nhap(),
                    pn.getSo_luong_nhap(),
                    pn.getDon_gia_nhap(),
                    pn.getVi_tri_vat_tu()
                    });
                }
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
 
    private void initComboBox() throws Exception{
        List<VATTU> listvt = new VatTuDao().findAll("");
        List<NHACC> listncc = new NhaCCDao().findAll();
        cbxidvt.removeAllItems();
        cbxidnhacc.removeAllItems();
        for(VATTU vt : listvt){
            cbxidvt.addItem(vt.getId_vt());
        }
        for(NHACC ncc : listncc){
            cbxidnhacc.addItem(ncc.getId_nhacc());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidpn = new javax.swing.JTextField();
        cbxidvt = new javax.swing.JComboBox<>();
        cbxidnhacc = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jdcngaynhap = new com.toedter.calendar.JDateChooser();
        txtsoluongnhap = new javax.swing.JTextField();
        txtdongianhap = new javax.swing.JTextField();
        btnMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtvitri = new javax.swing.JTextField();
        txtidnv = new javax.swing.JTextField();
        txttimkiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuNhap = new javax.swing.JTable();

        jpnRoot.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("ID phieu nhap");

        jLabel2.setText("ID vat tu");

        jLabel3.setText("ID nha cung cap");

        jLabel4.setText("ID nhan vien");

        txtidpn.setEditable(false);
        txtidpn.setBackground(new java.awt.Color(204, 204, 204));

        cbxidvt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxidnhacc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Ngay nhap");

        jLabel6.setText("So luong nhap");

        jLabel7.setText("Don gia nhap");

        jdcngaynhap.setDateFormatString("yyyy-MM-dd");

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-document.png"))); // NOI18N
        btnMoi.setText("Lam moi");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/floppy-disk.png"))); // NOI18N
        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        btnCapNhat.setText("Cap nhat");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel9.setText("Vi tri vat tu");

        txtidnv.setEditable(false);
        txtidnv.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidpn)
                            .addComponent(cbxidvt, 0, 112, Short.MAX_VALUE)
                            .addComponent(cbxidnhacc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtidnv))
                        .addGap(215, 215, 215)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdcngaynhap, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtsoluongnhap)
                            .addComponent(txtdongianhap)
                            .addComponent(txtvitri)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnMoi)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapNhat)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtidpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jdcngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxidvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtsoluongnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxidnhacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtdongianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(txtvitri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoi)
                    .addComponent(btnLuu)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/seo.png"))); // NOI18N
        btnTimKiem.setText("Tim kiem");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tblPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhieuNhap);

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        try {
            // TODO add your handling code here:
            txtidpn.setText(CreateID());
        } catch (Exception ex) {
            Logger.getLogger(NhapKho.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtidnv.setText(Login.id);
        jdcngaynhap.setDate(null);
        txtsoluongnhap.setText("");
        txtdongianhap.setText("");
        txtvitri.setText("");
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        loadDataToTable();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(txtidpn.getText().equals("")){
            sb.append("Ban chua nhap ID phieu nhap");
        }
        else if (txtsoluongnhap.getText().equals("")) {
            sb.append("Ban chua nhap so luong nhap");
        }
        else if (txtdongianhap.getText().equals("")) {
            sb.append("Ban chua nhap so don gia nhap");
        }
        else if (txtvitri.getText().equals("")) {
            sb.append("Ban chua nhap so luong nhap");
        }
        else if (new SimpleDateFormat("yyyy-MM-dd").format(jdcngaynhap.getDate()).equals("")) {
            sb.append("Ban chua nhap ngay nhap kho");
        }
        if(sb.length()>0){
           JOptionPane.showMessageDialog(this, sb);
           return;
        }
        try {
            PHIEUNHAP pn = new PHIEUNHAP();
            String id_vt = (String) cbxidvt.getItemAt(cbxidvt.getSelectedIndex());
            String id_nhacc = (String) cbxidnhacc.getItemAt(cbxidnhacc.getSelectedIndex());
            pn.setId_pn(txtidpn.getText());
            pn.setId_vt(id_vt);
            pn.setId_nhacc(id_nhacc);
            pn.setId_nv(Login.id);
            pn.setNgay_nhap(new SimpleDateFormat("yyyy-MM-dd").format(jdcngaynhap.getDate()));
            pn.setSo_luong_nhap(Integer.parseInt(txtsoluongnhap.getText()));
            pn.setDon_gia_nhap(Integer.parseInt(txtdongianhap.getText()));
            pn.setVi_tri_vat_tu(txtvitri.getText());
            if (new PhieuNhapDao().insert(pn)) {
                JOptionPane.showMessageDialog(this,"Phieu nhap da duoc them vao CSDL");
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Them khong thanh cong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Ban co muon cap nhat phieu nhap khong?") == JOptionPane.NO_OPTION){
            return;
        }
        try {
            PHIEUNHAP pn = new PHIEUNHAP();
            String id_vt = (String) cbxidvt.getItemAt(cbxidvt.getSelectedIndex());
            String id_nhacc = (String) cbxidnhacc.getItemAt(cbxidnhacc.getSelectedIndex());
            pn.setId_pn(txtidpn.getText());
            pn.setId_vt(id_vt);
            pn.setId_nhacc(id_nhacc);
            pn.setId_nv(Login.id);
            pn.setNgay_nhap(new SimpleDateFormat("yyyy-MM-dd").format(jdcngaynhap.getDate()));
            pn.setSo_luong_nhap(Integer.parseInt(txtsoluongnhap.getText()));
            pn.setDon_gia_nhap(Float.parseFloat(txtdongianhap.getText()));
            pn.setVi_tri_vat_tu(txtvitri.getText());

            if (new PhieuNhapDao().update(pn)) {
                JOptionPane.showMessageDialog(this,"Phieu nhap da duoc cap nhat vao CSDL");
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Cap nhat khong thanh cong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Ban co muon xoa phieu nhap khong?") == JOptionPane.NO_OPTION){
            return;
        }
        try {
            PhieuNhapDao dao = new PhieuNhapDao();
            if (dao.delete(txtidpn.getText())) {
                JOptionPane.showMessageDialog(this,"Phieu nhap da duoc xoa khoi CSDL");
                btnMoiActionPerformed(evt);
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Xoa khong thanh cong");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuNhapMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblPhieuNhap.getSelectedRow();
            int count_vt = cbxidvt.getItemCount();
            int count_nhacc = cbxidnhacc.getItemCount();

            if (row >= 0) {
                String id = (String) tblPhieuNhap.getValueAt(row, 0);
                PHIEUNHAP pn = new PhieuNhapDao().findByID(id);
                if (pn != null) {
                    txtidpn.setText(pn.getId_pn());
                    for(int i = 0; i < count_vt; i++){
                        if(pn.getId_vt() == null ? cbxidvt.getItemAt(i) == null : pn.getId_vt().equals(cbxidvt.getItemAt(i))){
                            cbxidvt.setSelectedIndex(i);
                        }
                    }
                    for(int i = 0; i < count_nhacc; i++){
                        if(pn.getId_nhacc() == null ? cbxidnhacc.getItemAt(i) == null : pn.getId_nhacc().equals(cbxidnhacc.getItemAt(i))){
                            cbxidnhacc.setSelectedIndex(i);
                        }
                    }
                    txtidnv.setText(pn.getId_nv());
                    jdcngaynhap.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(pn.getNgay_nhap()));
                    txtsoluongnhap.setText(String.valueOf(pn.getSo_luong_nhap()));
                    txtdongianhap.setText(String.valueOf(pn.getDon_gia_nhap()));
                    txtvitri.setText(pn.getVi_tri_vat_tu());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblPhieuNhapMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxidnhacc;
    private javax.swing.JComboBox<String> cbxidvt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcngaynhap;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JTable tblPhieuNhap;
    private javax.swing.JTextField txtdongianhap;
    private javax.swing.JTextField txtidnv;
    private javax.swing.JTextField txtidpn;
    private javax.swing.JTextField txtsoluongnhap;
    private javax.swing.JTextField txttimkiem;
    private javax.swing.JTextField txtvitri;
    // End of variables declaration//GEN-END:variables
}
