/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.VatTuDao;
import Model.VATTU;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import Dao.ConnectDB;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class VatTu extends javax.swing.JPanel {

    /**
     * Creates new form VatTu
     */
    private DefaultTableModel tblModel;
    private DefaultComboBoxModel cbxModel;
    public VatTu() {
        initComponents();
        initTable();
        loadDataToTable();
        initComboBox();
    }

    private String CreateID() throws Exception{
        List<VATTU> list = new VatTuDao().findAll("");  
        if (true) {
            int index = list.size()-1;
            VATTU vt = list.get(index);
            int idNumber = Integer.parseInt(vt.getId_vt().substring(2)) + 1; //id next        
            if (idNumber < 10) {
                return "vt00"+String.valueOf(idNumber);
            }
            else if (idNumber >= 10 && idNumber <100) {
                return "vt0"+String.valueOf(idNumber);
            }
            return "vt"+String.valueOf(idNumber);
        }
        return "vt001";
    }
    
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"ID vat tu","Ten vat tu","Loai vat tu","Don vi tinh","ID kho"});
        tblVatTu.setModel(tblModel);
    }
    
    private void loadDataToTable(){
        try {
            String key = txttimkiem.getText();
            VatTuDao dao = new VatTuDao();
            List<VATTU> list = dao.findAll(key);
            tblModel.setRowCount(0);
            for(VATTU vt : list){
                tblModel.addRow(new Object[]{
                    vt.getId_vt(),
                    vt.getTen_vt(),
                    vt.getLoai_vt(),
                    vt.getDon_vi_tinh(),
                    vt.getId_kho()
                });
            }
            System.out.println("id vat tu: "+key);
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void initComboBox(){
        try {
            String sql = "SELECT id_kho FROM KHO";
            Connection conn = ConnectDB.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            cbxidkho.removeAllItems();
            while(rs.next()){
                cbxidkho.addItem(rs.getString("id_kho"));
            }
            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtidvattu = new javax.swing.JTextField();
        txttenvattu = new javax.swing.JTextField();
        txtloaivt = new javax.swing.JTextField();
        txtdvt = new javax.swing.JTextField();
        cbxidkho = new javax.swing.JComboBox<>();
        btnMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVatTu = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/seo.png"))); // NOI18N
        btnTimKiem.setText("Tim kiem");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel1.setText("ID vat tu");

        jLabel2.setText("Ten vat tu");

        jLabel3.setText("Loai vat tu");

        jLabel4.setText("Don vi tinh");

        jLabel5.setText("ID kho");

        txtidvattu.setEditable(false);
        txtidvattu.setBackground(new java.awt.Color(204, 204, 204));

        txtloaivt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloaivtActionPerformed(evt);
            }
        });

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-document.png"))); // NOI18N
        btnMoi.setText("Lam moi");
        btnMoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/floppy-disk.png"))); // NOI18N
        btnLuu.setText("Luu");
        btnLuu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        btnCapNhat.setText("Cap nhat");
        btnCapNhat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnXoa.setText("Xoa");
        btnXoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtidvattu)
                    .addComponent(txttenvattu)
                    .addComponent(txtloaivt)
                    .addComponent(txtdvt)
                    .addComponent(cbxidkho, 0, 148, Short.MAX_VALUE))
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidvattu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttenvattu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtloaivt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(cbxidkho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblVatTu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblVatTu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVatTuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVatTu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtloaivtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloaivtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloaivtActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        try {
            // TODO add your handling code here:
            txtidvattu.setText(CreateID());
        } catch (Exception ex) {
            Logger.getLogger(VatTu.class.getName()).log(Level.SEVERE, null, ex);
        }
        txttenvattu.setText("");
        txtloaivt.setText("");
        txtdvt.setText("");
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(txtidvattu.getText().equals("")) sb.append("Ban chua nhap ID vat tu");
        else if(txttenvattu.getText().equals("")) sb.append("Ban chua nhap ten vat tu");
        else if(txtloaivt.getText().equals("")) sb.append("Ban chua nhap loai vat tu");
        else if(txtdvt.getText().equals("")) sb.append("Ban chua nhap dia don vi tinh");
        if(sb.length()>0){
           JOptionPane.showMessageDialog(this, sb);
           return;
        }
        try {
            VATTU vt = new VATTU();
            String id_kho = (String) cbxidkho.getItemAt(cbxidkho.getSelectedIndex());
            vt.setId_vt(txtidvattu.getText());
            vt.setTen_vt(txttenvattu.getText());
            vt.setLoai_vt(txtloaivt.getText());
            vt.setDon_vi_tinh(txtdvt.getText());
            vt.setId_kho(id_kho);
            if(new VatTuDao().insert(vt)){
                JOptionPane.showMessageDialog(this,"Vat tu da duoc them vao CSDL");
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Them khong thanh cong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Ban co muon cap nhat vat tu khong?") == JOptionPane.NO_OPTION){
            return;
        }
        
        try {
            VATTU vt = new VATTU();
            String id_kho = (String) cbxidkho.getItemAt(cbxidkho.getSelectedIndex());
            vt.setId_vt(txtidvattu.getText());
            vt.setTen_vt(txttenvattu.getText());
            vt.setLoai_vt(txtloaivt.getText());
            vt.setDon_vi_tinh(txtdvt.getText());
            vt.setId_kho(id_kho);
            if(new VatTuDao().update(vt)){
                JOptionPane.showMessageDialog(this,"Vat tu da duoc cap nhat vao CSDL");
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Cap nhat khong thanh cong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Ban co muon xoa vat tu khong?") == JOptionPane.NO_OPTION){
            return;
        }
        try {
            if (new VatTuDao().delete(txtidvattu.getText())) {
                JOptionPane.showMessageDialog(this,"Vat tu da duoc xoa khoi CSDL");
                btnMoiActionPerformed(evt);
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Xoa khong thanh cong");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblVatTuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVatTuMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblVatTu.getSelectedRow();
            if (row >= 0) {
                String id = (String) tblVatTu.getValueAt(row, 0);
                int c = cbxidkho.getItemCount();
                VATTU vt = new VatTuDao().findByID(id);
                System.out.println("id vat:" + id);
                if (vt != null) {
                    txtidvattu.setText(vt.getId_vt());
                    txttenvattu.setText(vt.getTen_vt());
                    txtloaivt.setText(vt.getLoai_vt());
                    txtdvt.setText(vt.getDon_vi_tinh());
                    System.out.println("id kho : "+vt.getId_kho());
                    for(int i =0  ; i < c; i++){
                        if(vt.getId_kho() == null ? (String) cbxidkho.getItemAt(i) == null : vt.getId_kho().equals((String) cbxidkho.getItemAt(i))){
                            cbxidkho.setSelectedIndex(i); 
                            break;
                        }
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblVatTuMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        loadDataToTable();
    }//GEN-LAST:event_btnTimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxidkho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVatTu;
    private javax.swing.JTextField txtdvt;
    private javax.swing.JTextField txtidvattu;
    private javax.swing.JTextField txtloaivt;
    private javax.swing.JTextField txttenvattu;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
