/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.KhachHangDao;
import Dao.NhanVienDao;
import Dao.PhieuXuatDao;
import Dao.TongVatTuDao;
import Dao.VatTuDao;
import Group.TONGVATTU;
import Model.KHACHHANG;
import Model.NHANVIEN;
import Model.PHIEUXUAT;
import Model.VATTU;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class XuatKho extends javax.swing.JPanel {

    /**
     * Creates new form XuatKho
     */
    private DefaultTableModel tblModel;
    private DefaultComboBoxModel cbxModel;
    public XuatKho() throws Exception {
        initComponents();
        initTable();
        loadDataToTable();
        initComboBox();
        if (Login.id.contains("ad")) {
            txtidnv.setText("");
        } else txtidnv.setText(Login.id);
    }
    
    private String CreateID() throws Exception{
        List<PHIEUXUAT> list = new PhieuXuatDao().findAll("");  
        if (list.size()!=0) {
            int index = list.size()-1;
            PHIEUXUAT px = list.get(index);
            int idNumber = Integer.parseInt(px.getId_px().substring(2)) + 1; //id next        
            if (idNumber < 10) {
                return "px00"+String.valueOf(idNumber);
            }
            else if (idNumber >= 10 && idNumber <100) {
                return "px0"+String.valueOf(idNumber);
            }
            return "px"+String.valueOf(idNumber);
            }
        return "px001";
    }
    
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"ID phieu xuat","ID vat tu","ID khach hang","ID nhan vien","Ngay xuat","So luong xuat","Don gia xuat",});
        tblPhieuXuat.setModel(tblModel);
    }
    
    private void loadDataToTable(){
        try {
            String key = txttimkiem.getText();
            PhieuXuatDao dao = new PhieuXuatDao();
            List<PHIEUXUAT> list = dao.findAll(key);
            tblModel.setRowCount(0);
            for(PHIEUXUAT px : list){
                if (px.getId_nv().contains(Login.id)) {
                    tblModel.addRow(new Object[]{
                    px.getId_px(),
                    px.getId_vt(),
                    px.getId_kh(),
                    px.getId_nv(),
                    px.getNgay_xuat(),
                    px.getSo_luong_xuat(),
                    px.getDon_gia_xuat(),
                    });
                }
                else if (Login.id.contains("ad")) {
                    tblModel.addRow(new Object[]{
                    px.getId_px(),
                    px.getId_vt(),
                    px.getId_kh(),
                    px.getId_nv(),
                    px.getNgay_xuat(),
                    px.getSo_luong_xuat(),
                    px.getDon_gia_xuat(),
                    });
                }
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void initComboBox() throws Exception{
        List<VATTU> listvt = new VatTuDao().findCBX();
        List<KHACHHANG> listkh = new KhachHangDao().findAll();
        cbxidvt.removeAllItems();
        cbxidkh.removeAllItems();
        for(VATTU vt : listvt){
            cbxidvt.addItem(vt.getId_vt());
        }
        for(KHACHHANG kh : listkh){
            cbxidkh.addItem(kh.getId_kh());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidpx = new javax.swing.JTextField();
        cbxidvt = new javax.swing.JComboBox<>();
        cbxidkh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jdcngayxuat = new com.toedter.calendar.JDateChooser();
        txtsoluongxuat = new javax.swing.JTextField();
        txtdongiaxuat = new javax.swing.JTextField();
        btnMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtidnv = new javax.swing.JTextField();
        txttimkiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuXuat = new javax.swing.JTable();

        jpnRoot.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setText("ID phieu xuat");

        jLabel2.setText("ID vat tu");

        jLabel3.setText("ID khach hang");

        jLabel4.setText("ID nhan vien");

        txtidpx.setEditable(false);
        txtidpx.setBackground(new java.awt.Color(204, 204, 204));

        cbxidvt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxidkh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Ngay xuat");

        jLabel6.setText("So luong xuat");

        jLabel7.setText("Don gia xuat");

        jdcngayxuat.setDateFormatString("yyyy-MM-dd");

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new-document.png"))); // NOI18N
        btnMoi.setText("Lam moi");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/floppy-disk.png"))); // NOI18N
        btnLuu.setText("Luu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        btnCapNhat.setText("Cap nhat");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txtidnv.setEditable(false);
        txtidnv.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnMoi)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapNhat)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtidnv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidpx, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxidvt, javax.swing.GroupLayout.Alignment.LEADING, 0, 112, Short.MAX_VALUE)
                            .addComponent(cbxidkh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(215, 215, 215)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdcngayxuat, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtsoluongxuat)
                            .addComponent(txtdongiaxuat))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtidpx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jdcngayxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxidvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtsoluongxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxidkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtdongiaxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtidnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoi)
                    .addComponent(btnLuu)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/seo.png"))); // NOI18N
        btnTimKiem.setText("Tim kiem");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        tblPhieuXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhieuXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuXuatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhieuXuat);

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        try {
            txtidpx.setText(CreateID());
        } catch (Exception ex) {
            Logger.getLogger(XuatKho.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtidnv.setText(Login.id);
        txtdongiaxuat.setText("");
        txtsoluongxuat.setText("");
        jdcngayxuat.setDate(null);
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        loadDataToTable();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if(txtidpx.getText().equals("")){
            sb.append("Ban chua nhap ID phieu xuat");
        }
        else if (txtsoluongxuat.getText().equals("")) {
            sb.append("Ban chua nhap so luong xuat");
        }
        else if (txtdongiaxuat.getText().equals("")) {
            sb.append("Ban chua nhap so luong xuat");
        }
        else if (new SimpleDateFormat("yyyy-MM-dd").format(jdcngayxuat.getDate()).equals("")) {
            sb.append("Ban chua nhap ngay xuat kho");
        }
        if(sb.length()>0){
           JOptionPane.showMessageDialog(this, sb);
           return;
        }
        try {
            PHIEUXUAT px = new PHIEUXUAT();
            String id_vt = (String) cbxidvt.getItemAt(cbxidvt.getSelectedIndex());
            String id_kh = (String) cbxidkh.getItemAt(cbxidkh.getSelectedIndex());
            px.setId_px(txtidpx.getText());
            px.setId_vt(id_vt);
            px.setId_kh(id_kh);
            px.setId_nv(Login.id);
            px.setNgay_xuat(new SimpleDateFormat("yyyy-MM-dd").format(jdcngayxuat.getDate()));
            px.setSo_luong_xuat(Integer.parseInt(txtsoluongxuat.getText()));
            px.setDon_gia_xuat(Integer.parseInt(txtdongiaxuat.getText()));
            
            TONGVATTU ttv = new TongVatTuDao().checkSL(id_vt);
            int slmax = ttv.getTong_sln() - ttv.getTong_slx() - ttv.getTong_slt();
            if (Integer.parseInt(txtsoluongxuat.getText()) > slmax) {
                JOptionPane.showMessageDialog(this,"so luong xuat <= " + String.valueOf(slmax) ,"canh bao",JOptionPane.ERROR_MESSAGE);
            } else{
                if (new PhieuXuatDao().insert(px)) {
                JOptionPane.showMessageDialog(this,"Phieu xuat da duoc them vao CSDL");
                loadDataToTable();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Them khong thanh cong");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Ban co muon cap nhat phieu xuat khong?") == JOptionPane.NO_OPTION){
            return;
        }
        try {
            PHIEUXUAT px = new PHIEUXUAT();
            String id_vt = (String) cbxidvt.getItemAt(cbxidvt.getSelectedIndex());
            String id_kh = (String) cbxidkh.getItemAt(cbxidkh.getSelectedIndex());
            px.setId_px(txtidpx.getText());
            px.setId_vt(id_vt);
            px.setId_kh(id_kh);
            px.setId_nv(Login.id);
            px.setNgay_xuat(new SimpleDateFormat("yyyy-MM-dd").format(jdcngayxuat.getDate()));
            px.setSo_luong_xuat(Integer.parseInt(txtsoluongxuat.getText()));
            px.setDon_gia_xuat(Float.parseFloat(txtdongiaxuat.getText()));
            
            TONGVATTU ttv = new TongVatTuDao().checkSL(id_vt);
            int slmax = ttv.getTong_sln() - ttv.getTong_slx() - ttv.getTong_slt();
            if (Integer.parseInt(txtsoluongxuat.getText()) > slmax) {
                JOptionPane.showMessageDialog(this,"so luong xuat <= " + String.valueOf(slmax) ,"canh bao",JOptionPane.ERROR_MESSAGE);
            } else{
                if (new PhieuXuatDao().update(px)) {
                JOptionPane.showMessageDialog(this,"Phieu xuat da duoc cap nhat vao CSDL");
                loadDataToTable();
                }
                else{
                    JOptionPane.showMessageDialog(this,"cap nhat khong thanh cong");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this,"Ban co muon xoa phieu xuat khong?") == JOptionPane.NO_OPTION){
            return;
        }
        try {
            if (new PhieuXuatDao().delete(txtidpx.getText())) {
                JOptionPane.showMessageDialog(this,"Phieu xuat da duoc xoa khoi CSDL");
                btnMoiActionPerformed(evt);
                loadDataToTable();
            }
            else{
                JOptionPane.showMessageDialog(this,"Xoa khong thanh cong");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblPhieuXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuXuatMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblPhieuXuat.getSelectedRow();
            int count_vt = cbxidvt.getItemCount();
            int count_kh = cbxidkh.getItemCount();

            if (row >= 0) {
                String id = (String) tblPhieuXuat.getValueAt(row, 0);
                PHIEUXUAT pn = new PhieuXuatDao().findByID(id);
                if (pn != null) {
                    txtidpx.setText(pn.getId_px());
                    for(int i = 0; i < count_vt; i++){
                        if(pn.getId_vt() == null ? cbxidvt.getItemAt(i) == null : pn.getId_vt().equals(cbxidvt.getItemAt(i))){
                            cbxidvt.setSelectedIndex(i);
                        }
                    }
                    for(int i = 0; i < count_kh; i++){
                        if(pn.getId_kh() == null ? cbxidkh.getItemAt(i) == null : pn.getId_kh().equals(cbxidkh.getItemAt(i))){
                            cbxidkh.setSelectedIndex(i);
                        }
                    }
                    txtidnv.setText(pn.getId_nv());
                    jdcngayxuat.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(pn.getNgay_xuat()));
                    txtsoluongxuat.setText(String.valueOf(pn.getSo_luong_xuat()));
                    txtdongiaxuat.setText(String.valueOf(pn.getDon_gia_xuat()));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblPhieuXuatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxidkh;
    private javax.swing.JComboBox<String> cbxidvt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcngayxuat;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JTable tblPhieuXuat;
    private javax.swing.JTextField txtdongiaxuat;
    private javax.swing.JTextField txtidnv;
    private javax.swing.JTextField txtidpx;
    private javax.swing.JTextField txtsoluongxuat;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
